### ISSUE TITLE
various suggestions to assist in program usage

### ISSUE THREAD

**Issue by nataliemeow** [heav-4/relocation#1]
1. a grid
2. a semi-transparent preview of the batch currently being held. this would maybe have a border that would change color according to if the placement is valid
3. zooming?

sidenote: might write a PR

**Comment by heav-4** [comment]
these are all fairly good ideas. zooming is lower priority than the other ones maybe but i will consider all of them.

**Comment by heav-4** [comment]
zooming is addressed.

**Comment by heav-4** [comment]
i don't think i'm going to make the semi-transparent preview for reasons, so i suppose i'm done with this one.

**Comment by nataliemeow** [comment]
coolio
